name: TestAmplification
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  reponame: ${{github.event.repository.name}}
  project_baseline: SmallBank
  project_directory: src
  iteration: 3
  SMALLAMP_NOPUSH: PUSH
  SMALLAMP_MaxCrash: 10
  # check image freeze each 4*60 sec: a normal test method has a 3 minute time out
  SMALLAMP_freezeTimeOut: 120
  SmallAmp_ShredSeed: ${{ github.run_id}}
  SMALLAMP_DashboardJson: 1

on:
  workflow_dispatch:
    inputs:
      testClasses:
        description: 'TestClasses to amplify (comma separated) empty-> all'
        required: false
        default: 'SmallBankTest'
      mode:
        description: 'mode (dspot, dspotFast, dspotFastRank)'
        required: true
        default: 'dspotFastRank'
      parallel_jobs:
        description: 'Max number of all parallel jobs (0 use Input testClasses length)'
        required: true
        default: '1'
      maxInputs:
        description: 'Number of test variant per original test'
        required: true
        default: '10'
      shreds:
        description: 'Maximum number of methods per test class (0 means no shreding)'
        required: true
        default: '15'
      timeBudget:
        description: 'Number of minutes as time budget per test class (0 means no limit)'
        required: true
        default: '5'
jobs:
  MatrixBuild:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.result }}
    steps:
      - name: configurations
        run: |
          echo "testClasses -> ${{github.event.inputs.testClasses}}"
          echo "mode -> ${{github.event.inputs.mode}}"
          echo "parallel_jobs -> ${{github.event.inputs.parallel_jobs}}"
          echo "maxInputs -> ${{github.event.inputs.maxInputs}}"
          echo "timeBudget -> ${{github.event.inputs.timeBudget}}"
      - id: set-matrix
        uses: actions/github-script@v4
        env:
          testClasses: ${{ github.event.inputs.testClasses }}
          parallel_jobs: ${{ github.event.inputs.parallel_jobs }}
        with:
          script: |
            l = parseInt(process.env.parallel_jobs)
            if(l==0){
              if(process.env.testClasses){
                if (process.env.testClasses.split(',').length < l )
                  l = process.env.testClasses.split(',').length
              }
            }
            a = Array.from({length: l}, (x, i) => {a:i});
            var o = {jobs: a};
            return o

  TestAmplification:
    needs: MatrixBuild
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.MatrixBuild.outputs.matrix)}}
#        portion: [1 , 2, 3, 4, 5, 6, 7, 8] # Change me if you like to run in parallel. The content of array is not important, just the length
    name: Job number ${{ strategy.job-index }}
    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - uses: mabdi/smallamp-action@main
        with:
          action: setup
      - uses: mabdi/smallamp-action@main
        with:
          action: amplify
        env:
          SMALLAMP_PORTION: ${{ strategy.job-index }}
          SMALLAMP_ALLJOBS: ${{ strategy.job-total }}
          SMALLAMP_iteration: ${{ env.iteration }}
          SMALLAMP_maxInputs: ${{ github.event.inputs.maxInputs }}
          SMALLAMP_SHREDS: ${{ github.event.inputs.shreds }}
          SMALLAMP_mode: ${{ github.event.inputs.mode }}
          SMALLAMP_timeBudget: ${{ github.event.inputs.timeBudget }}
          SMALLAMP_testClasses: ${{ github.event.inputs.testClasses }}

  TestAmplificationPush:
    runs-on: ubuntu-latest
    needs: TestAmplification
    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - uses: mabdi/smallamp-action@main
        with:
          action: setup
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{ env.PHARO_HOME }}
      - uses: mabdi/smallamp-action@main
        with:
          action: push
          github-token: ${{secrets.GITHUB_TOKEN}}
        env:
          iteration: ${{ env.iteration }}
          maxInputs: ${{ github.event.inputs.maxInputs }}
          shreds: ${{ github.event.inputs.shreds }}
          mode: ${{ github.event.inputs.mode }}
          timeBudget: ${{ github.event.inputs.timeBudget }}
          testClasses: ${{ github.event.inputs.testClasses }}
          parallel_jobs: ${{ github.event.inputs.parallel_jobs }}
